### Recuperar todas las peliculas
GET  http://localhost:3000/api

### Recuperar todas las tracks
GET  http://localhost:3000/api/tracks

### Crear un track
POST  http://localhost:3000/api/tracks
Content-Type: application/json

{
  "name": "Allen",
  "album": "Album",
  "cover": "http://tttt.com",
  "artist": {
    "name": "Allen",
    "nickname": "frozst",
    "nationality": "BO"
  },
  "duration": {
    "start": 1,
    "end": 0
  },
  "mediaId": "621e7499a1f699063f5114bc"
}

### Recuperar un track por id
GET  http://localhost:3000/api/tracks/653ae6dfaefe88cfa970e09a

### Actualizar un track
PUT  http://localhost:3000/api/tracks/653ae6dfaefe88cfa970e09a
Content-Type: application/json

{
  "name": "Nathan",
  "album": "Album B",
  "cover": "http://zzzz.com",
  "artist": {
    "name": "Nathan",
    "nickname": "TheFrozst",
    "nationality": "ESP"
  },
  "duration": {
    "start": 1,
    "end": 0
  },
  "mediaId": "621e7499a1f699063f5114bc"
}

### Eliminar un track por id
DELETE  http://localhost:3000/api/tracks/6542f198e74ba54d211bb7a4